config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  root to: 'pages#home'
  get 'dashboard', to: 'homepages#dashboard', as: :dashboard
  get 'chatbox', to: 'watch_parties#chatbox', as: :chatbox
  # get 'movies/id', to: 'movies#show'
  # get 'movies/id/trailer', to: 'movies#show'
  # post 'watch-parties/attendees', to: 'attendees#create'
  # get 'watch-parties/new', to: 'watch_parties#new'
  # post 'messages', to: 'messages#create'
  # get 'movie/id', to: 'movies#show'
  # post 'movie/id/reviews', to: 'reviews#create'
  # get 'movie/id/reviews', to: 'reviews#show', as: :review
  # get 'home', to: 'homepages#home'


  resources :movies, only: [:show] do
    resources :reviews, only: [:new, :create]
  end

  resources :watch_parties, only: [:new, :create, :show, :index, :destroy] do
    resources :messages, only: [:new, :create, :show, :index]
    resources :attendees, only: [:create]
  end

  resources :attendees, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  has_many :messages
  belongs_to :user
  belongs_to :watch_party
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :attendee
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :watch_parties, dependent: :destroy
  has_one_attached :photo
  belongs_to :movie_date
end

app/models/movie_date.rb
class MovieDate < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :watch_parties
  has_many :attendees
  has_many :attending_watch_parties, through: :attendees, source: :watch_party
  has_many :reviews
  has_one_attached :avatar
 # validates :avatar, file_size: { less_than_or_equal_to: 5.megabytes },
  #            file_content_type: { allow: ['image/jpeg', 'image/png', 'image/gif'] }
end

app/models/watch_party.rb
class WatchParty < ApplicationRecord
  belongs_to :user
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  belongs_to :movie
  has_many :attendees
  has_many :messages, through: :attendees

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(dashboard)
    dashboard_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar])
  end
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  def create
    @attendee = Attendee.new
    @attendee.user = current_user
    @watch_party = WatchParty.find params[:watch_party_id]
    @attendee.watch_party = @watch_party
    @attendee.save!
    redirect_to watch_party_path @watch_party
  end

  def index
    @attendees = Attendee.all
  end

  def show
    @attendee = Attendee.find(params[:id])
  end

  def destroy
    @attendee = Attendee.find(params[:id])
    @attendee.destroy
    redirect_to watch_parties_path format: "chatbox"
  end

end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  def dashboard
    @movies = Movie.all
  end

  # def index
  #   @movie = Movie.all
  # end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
    @message = Message.new
  end

  def create
    @watch_party = WatchParty.find(params[:watch_party_id])
    @message = Message.new(message_params)
    @message.attendee = current_user.attendees.find_by(watch_party: @watch_party)
    if @message.save!
      WatchPartyChannel.broadcast_to(
        @watch_party,
        render_to_string(partial: "message", locals: { message: @message })
      )
      redirect_to watch_party_path(@watch_party, anchor: "message-#{@message.id}")
    else
      render "watch_party/show"
    end
  end

  private

  def message_params
    params.require(:message).permit(:watch_party_id, :attendee_id, :content)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
    @review
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ], raise: false

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @movie = Movie.find(params[:movie_id])
    @review = Review.new
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @review = Review.new(review_params)
    @review.movie_id = @movie.id
    @review.user = current_user
    if @review.save!
      redirect_to movie_path(@movie)
    else
      render 'movie/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :movie_id, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end

  def index
    if params[:query].present?
      @users = User.where("location ILIKE ?", "%#{params[:query]}%")
    else
      @users = User.all
    end
  end

  def destroy
    @user.destroy
    redirect_to watch_party_path(@watch_party.user)
  end
end

app/controllers/watch_parties_controller.rb
class WatchPartiesController < ApplicationController
  def new
    @watch_party = WatchParty.new
  end

  def create
    @watch_party = WatchParty.new(watch_party_params)
    @watch_party.user = current_user
    if @watch_party.save!
      redirect_to watch_party_path(@watch_party)
    else
      render "new"
    end
  end

  def show
    @watch_party = WatchParty.find(params[:id])
    @message = Message.new
    @markers =  [{
        lat: @watch_party.latitude,
        lng: @watch_party.longitude,
        info_window: render_to_string(partial: "info_window", locals: { watch_party: @watch_party })
      }]
  end

  def index
    if params[:format].present?
      @watch_parties = current_user.attending_watch_parties
    else
      @watch_parties = WatchParty.all
    end
    @markers = @watch_parties.geocoded.map do |watch_party|
      {
        lat: watch_party.latitude,
        lng: watch_party.longitude,
        info_window: render_to_string(partial: "info_window", locals: { watch_party: watch_party })
      }
    end
  end

  def destroy
    @watch_party = WatchParty.find(params[:id])
    @watch_party.destroy
    redirect_to watch_parties_path
  end

  private

  def watch_party_params
    params.require(:watch_party).permit(:title, :content, :location, :date, :name, :movie_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepages/dashboard.html.erb
<div data-controller="dashboard">
  <div class="banner" style="background-image: linear-gradient(to left, rgba(0,0,0,0),rgba(0,0,0,1) 130%), url(<%= image_path(@movies.last.picture) %>);">
    <div class="filmoftheday">



      <h1 class="day"> Movie of the day</h1>
      <div class="movieinfo">
      <p class="movietitle"><%=@movies.last.title %></p>
      <p class="overview"><%= @movies.last.overview %></p>
      <div class=spaceyear>
      <p class="director">Director: <%= @movies.last.director %></p>
      <p class="year">Year: <%= @movies.last.year %></p>
      <p class="rating">Rating: <%= @movies.last.rating %></p>
      </div>
      <%= link_to "Watch the movie", movie_path(@movies.last), class: "btn btn-primary" %>
      <%= link_to "Discover Watch Parties", watch_parties_path, class: "btn btn-primary secondary" %>
      </div>
      <a href="#movie-list"> <i class="fas fa-angle-double-down"></i> </a>

    </div>
  </div>
  <div class="container-flud">
    <div style="display: flex;
      flex-wrap: wrap;" id="movie-list">
        <% @movies.sort_by { |x| x.movie_date.start_date}.reverse.each do |movie| %>
          <% unless movie == @movies.last %>
            <div class="col-sm-12 col-md-4">
              <%= link_to movie_path(movie), class: "title" do %>
                <div class="card text-center" style="background-image: url('<%= image_path(movie.picture) %>');" data-image-url="<%= image_path(movie.picture) %>" data-dashboard-target="poster" data-action="mouseover->dashboard#showInfo mouseout->dashboard#hideInfo">
                  <h2 class="d-none title"><%= movie.title %></h2>
                </div>
              <% end %>
            </div>

          <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>FilmWeek</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%# <%= favicon_link_tag %>
  </head>

  <body>
    <div class="main-content">
      <%= render 'shared/navbar' unless params[:action] == "home" || devise_controller? %>
      <%= render 'shared/flashes' %>

      <%= yield %>
      <%= render "shared/footer" %>
    </div>
  </body>

</html>

app/views/messages/_message.html.erb
<div class="message-container" id="message-<%= message.id %>">
  <i class="author">
    <span><%= message.attendee.user.username %></span>
    <small><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></small>
  </i>
  <p><%= message.content %></p>
</div>

app/views/messages/show.html.erb
<div class="message-container" id="message-<%= message.id %>">
  <i class="author">
    <span><%= message.user.nickname %></span>
    <small><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></small>
  </i>
  <p><%= message.content %></p>
</div>

app/views/movies/show.html.erb
<div class="movie-background" style="background-image: linear-gradient(80deg, rgba(0,0,0,0.9) 0%, rgba(0,0,0,0) 100%), url('<%= image_path(@movie.picture_2) %>')">
  <h1>
    <%= @movie.title %>
  </h1>

  <div class="movie-info">
    <p class="d-flex justify-content-around" style="min-width: 25vw"> <span class="w-25 text-left"> Director </span> <span class="w-50 text-left" ><%= @movie.director %> </span> </p>
    <p class="d-flex justify-content-around" style="min-width: 25vw"> <span class="w-25 text-left"> Starrring </span> <span class="w-50 text-left"> <%= @movie.actor %> </span>  </p>
    <p class="d-flex justify-content-around" style="min-width: 25vw"> <span class="w-25 text-left"> Synopsis </span> <span class="w-50 text-left"> <%= @movie.synopsis %> </span>  </p>
    <p class="d-flex justify-content-around" style="min-width: 25vw"> <span class="w-25 text-left"> Movie Year </span> <span class="w-50 text-left"> <%= @movie.year %> </span>  </p>
    <p class="d-flex justify-content-around" style="min-width: 25vw"> <span class="w-25 text-left"> Rating </span> <span class="w-50 text-left"> <%= @movie.rating %> </span>  </p>
    <p class="d-flex justify-content-around" style="min-width: 25vw"> <span class="w-25 text-left"> Trailer</span>
      <span class="w-50 text-left">
        <a class="trailer" data-toggle="modal" data-target="#trailerModal">
           Watch Trailer
        </a>
        <div class="modal fade" id="trailerModal" tabindex="-1" role="dialog" aria-labelledby="trailerModalLabel" aria-hidden="true">
          <div class="modal-dialog .modal-xl modal-dialog-centered" role="document">
            <div class="modal-content">
              <iframe
                  width="800"
                  height="500"
                  src="<%= @movie.movie_url %>"
                  title="YouTube video player"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                  allowfullscreen>
              </iframe>
            </div>
          </div>
      </span>
    </p>
  </div>


  <div class="button-info">
    <!-- Full Movie Modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#fullmovieModal">
      Watch Full Movie
    </button>
    <div class="modal fade" id="fullmovieModal" tabindex="-1" role="dialog" aria-labelledby="fullmovieModalLabel" aria-hidden="true">
      <div class="modal-dialog .modal-xl modal-dialog-centered" role="document">
        <div class="modal-content">
          <iframe
              width="800"
              height="500"
              src="<%= @movie.movie_url %>"
              title="YouTube video player"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen>
          </iframe>
        </div>
      </div>
    </div>
    <!-- Watch Party Link -->
    <div>
      <%= link_to "Create Watch Party", new_watch_party_path, class:"btn btn-primary secondary" %>
    </div>
  </div>
</div>
</div>

app/views/pages/home.html.erb
<%# <div class="texth">
  <h1>Filmweek</h1>
  <p>A selection of great movies availbale anywhere, anytime </p>
</div>
 %>



<div class="home-page">
<header class="showcase">
			<div class="showcase-top">
				  <h1 class="logo">FILM WEEK</span> <i class="fas fa-video"></i></h1>
        <%= link_to "Log In", user_session_path, class: "btn btn-rounded"%>
			</div>
			<div class="showcase-content">
				<h1>A selection of <strong>7</strong> great movies</h1>
				<p>Watch anywhere, anytime</p>
        <%= link_to "SIGN UP!", new_user_registration_path, class: "btn btn-xl"%>
			</div>
		</header>

		<section class="tabs">
			<div class="container1">
				<div id="tab-1" class="tab-item tab-border">
					<i class="fas fa-ban"></i>
					<p class="hide-sm">Cancel at any time</p>
				</div>
				<div id="tab-2" class="tab-item">
					<i class="fas fa-glass-cheers"></i>
					<p class="hide-sm">Discover watchparties</p>
				</div>
				<div id="tab-3" class="tab-item">
					<i class="fas fa-comments"></i>
					<p class="hide-sm">Chat with other movie-enthousiasts</p>
				</div>
			</div>
		</section>
</div>

app/views/reviews/new.html.erb
<div class="container">
<p>Dear Customer,<br>
Thank you for watching the movie! Please spare some moments to give us your valuable feedback about the movie.</p>

<label> What are your thoughts about the movie?</label><br>
  <div class="row">
    <div class="col-xs-4">
      <%= simple_form_for [@movie, @review ] do |f| %>
        <%= f.input :comment %>
        <%= f.input :rating, collection: (1..5).to_a, label: "How would you rate the movie" %>
        <%= f.submit "Send your review" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Copyright © 2013-2021 Film Week Inc. All Rights Reserved.
    <a href="#">Terms and Conditions</a> and <a href="#">Privacy &amp; Cookie Policy</a>.
    <br>
    watch a great movie <i class="fas fa-heart"></i> with Film Week.
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="header">
  <div class="logo">
  <%= link_to dashboard_path do %>
    <%= image_tag "logo.png", id:"logo" %>
    <% end %>
  </div>

  <div>
    <ul class="navigation">
      <li><%= link_to "Home", dashboard_path %></li>
      <li><%= link_to "Watchparties", watch_parties_path %></li>
      <li class="dropdown"> Our Movie
        <div class="dropdown-content">
        <% Movie.all.each do |movie| %>
          <%= link_to movie.title, movie_path(movie) %>
        <% end %>
        </div>
      </li>
    </ul>
  </div>

  <div class="dropdown">
    <% if current_user.avatar.attached? %>
      <%= cl_image_tag current_user.avatar.key, class: 'avatar-user' %>
    <% else %>
      <%= image_tag "avatardefault.png", class: 'avatar-default' %>
    <% end %>

    <div>
        <ul class="dropdown-content">
          <% if user_signed_in? %>
            <li class="username"> Log in as <%= current_user.username %></li>
            <li><%= link_to 'User Profile', edit_user_registration_path, :class => 'navbar-link' %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %></li>
            <li><%= link_to "Login", new_user_session_path, class: 'navbar-link' %></li>
          <% end %>
        </ul>
    </div>
  </div>

</div>

app/views/users/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/random);">
  <div class="container">
    <h1>User Profile</h1>
    <p>Find your details below</p>
  </div>
</div>

<div class="container">
<div class="row">
<div class="col-xs-12 col-sm-4 col-sm-offset-4">
<p>Email: <%= @user.email %> </p>
<p>Username: <%=  @user.username %> </p>
<p>User id: <%=  @user.id %> </p>
</div>

</div>
</div>

<%= link_to "Edit information", to:  edit_user_registration_path %>

app/views/watch_parties/_info_window.html.erb
<div class="map-marker">
  <%= image_tag "avatardefault.png", class: 'map-marker-image' %>
  <br>
  <p>Name:</p>
  <p><%= watch_party.name %></p>
  <br>
  <p>Location:</p>
  <p><%= watch_party.location %></p>
</div>

app/views/watch_parties/index.html.erb
  <div class= ban>
    <h1 class="text-main">Find a watch party in your neighbourhood</h1>
    <div class= start>
      <div class="vertical-center">
        <%= link_to "Or create your own watch party!", new_watch_party_path, class:"btn btn-primary" %>
      </div>
    </div>
  </div>

  <div class= both-wings>
    <div class="left-wing all-movies">
      <% @watch_parties.each_with_index do |watch_party| %>
        <div class="box-row">
          <%= image_tag watch_party.movie.picture, id: 'mov-img' %>
            <div class= 'info'>
              <h4><%= watch_party.movie.title%></h4>
              <p><%= watch_party.location %></p>
              <p><%= watch_party.date %></p>
            </div>
            <div class= 'info-btn'>
              <%= link_to "Register", watch_party_attendees_path(watch_party),
              method: :post, id: 'join-link' %>
            </div>
        </div>
          <% end %>
      </div>

      <div class= right-wing>
          <div id="map"
                style="width: 100%; height: 97vh;"
                data-markers="<%= @markers.to_json %>"
                data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
            </div>
      </div>
  </div>

app/views/watch_parties/new.html.erb
<div class="form-party">
    <%= simple_form_for(@watch_party) do |f| %>
    <%= f.input :name %>
    <%= f.association :movie %>
    <%= f.input :content %>
    <%= f.input :location %>
    <%= f.input :date %>
    <%= f.submit "Create Watch Party", class: "btn btn-primary"%>
  <% end %>
</div>

app/views/watch_parties/show.html.erb
  <div id="banner">
    <h1><b><%= @watch_party.name %></b></h1>
      <div class= banner-all>
        <div class= "banner-box">
          <div class= "avatar">
            <%= cl_image_tag @watch_party.user.avatar.key, id: 'host-img' %>
          </div>
          <div class= "page-header">
            <h3> Hosted by <%= @watch_party.user.username %> </h3>
            <p><%= @watch_party.date.strftime("%a %b %e at %l:%M%p")  %></p>
            <p><%= @watch_party.location %></p>
            <button type="button" class="btn btn-primary my" data-toggle="modal" data-target="#fullmovieModal">
            <%=mail_to @watch_party.user.email, 'Contact the host' %>
            </button>
          </div>
        </div>
      </div>
  </div>

<div class="main">

    <div class= left-elements>
        <div class= "content">
          <h3><b>Description</b></h3>
          <%= @watch_party.content %>
        </div>
              <div class= chat-box>
          <h3><b>Chatroom</b></h3>
          <div id="messages" data-watch_party-id="<%= @watch_party.id %>">
              <% @watch_party.messages.each do |message| %>
                <div class="message-container" id="message-<%= message.id %>">
                  <i class="author">
                    <span><%= message.attendee.user.username %></span>
                    <small><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></small>
                  </i>
                  <p><%= message.content %></p>
                </div>
              <% end %>
          </div>

          <%= simple_form_for [ @watch_party, @message ], remote: true do |f| %>
            <%= f.input :content, label: false, placeholder: "Message #{@watch_party.name}", input_html: { style: "width: auto;"} %>
            <%= f.button :submit, :label => 'Assign', class: "btn btn-default btn-primary" %>
          <% end %>

      </div>
        <div class="attendees">
          <h3><b> Attending</b></h3>
        <div class= user-cards>
          <% @watch_party.attendees.each do |attendee| %>
            <div class= card-style>
            <%= cl_image_tag attendee.user.avatar.key, id: 'user-avatar' %>
            <%= attendee.user.username %>
            </div>
          <% end %>
        </div>
      </div>

    </div>



    <div class= 'right-elements ml-4'>
        <div class= little-box-1>
          <div class= "movie-img">
           <%= image_tag(@watch_party.movie.picture) %>
          </div>
          <div class= "movie-inf">
            <h3><b><%= @watch_party.movie.title %></b> </h3>
            <p class="director">Director: <%= @watch_party.movie.director %></p>
            <p class="year">Year: <%= @watch_party.movie.year %></p>
            <p class="rating">Rating: <%= @watch_party.movie.rating %></p>
          </div>
        </div>




        <div class= little-box-2>
          <div class= map-info>
            <div id="map"
              style="height: 350px; width: 23vw;"
              data-markers="<%= @markers.to_json %>"
              data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
            </div>
            <div class="container">
              <i class="far fa-clock"></i>
              <p><%= @watch_party.date.strftime("%a %b %e at %l:%M%p")%></p>
              <i class="fas fa-map-marker"></i>
              <p><%=@watch_party.location %></p>
            </div>
          </div>
        </div>
    </div>
</div>